<?php
$config = array(
    'import'=>array(
        'models.*',
        'zabbix.*'
    ),
    'database'=>array(
        'db'=>array(
            'dbhost'=>'localhost',
            'dbuser'=>'root',
            'dbpasswd'=>'',
            'dbname'=>'server',
            'dbpconnect'=>0,
            'dbchart'=>'utf8'
        ),
        'db2'=>array(
            'dbhost'=>'localhost',
            'dbuser'=>'root',
            'dbpasswd'=>'',
            'dbname'=>'joke',
            'dbpconnect'=>0,
            'dbchart'=>'utf8'
        )
    )
);
?>